name: homeflix

services:
  jellyfin:
    image: linuxserver/jellyfin:amd64-latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VIRTUAL_HOST=jellyfin
      - VIRTUAL_PORT=8096
    volumes:
      - ./config/jellyfin:/config
      - /media:/media
    ports:
      - 8096:8096
    restart: always